### ISSUE TITLE
test: does not have 100% coverage

### ISSUE THREAD

**Issue by bbartolome** [eq8/redbloom#2]
Currently, the test only has 94.11% coverage and is missing coverage for this code path:
https://github.com/eq8/redbloom/blob/e1bf9f92261ac1c1790a005247b98813724626dd/index.js#L23

Something simple should suffice. I figured this could be an easy upcount for your hacktoberfest PR count ;)

**Edit:** The expected behaviour is that if an unregistered action was dispatch, it should not change the current state.

Thanks in advance!

**Comment by manishrw** [comment]
I can take it up :-)

**Comment by edwaraco** [comment]
:( I'm sorry so much. I've created the PR https://github.com/eq8/redbloom/pull/4 as solution for this issues. I have been worked from yesterday.

**Comment by bbartolome** [comment]
@earayo no problem :) I've reviewed your PR if you're still willing to work on it.

@manishrw please feel free. I'm open to accept the best implementation.

I've also updated the description to reflect the expected behaviour.
